finish step2
AlekseiZhukov/Lumincoin-finance-js pull request #1
Opened 2024-02-07 09:35 UTC by AlekseiZhukov

Закончил второй этап проекта

2024-02-07 11:26 UTC, Amil-Gaoul requested changes

2024-02-07 11:26 UTC, Amil-Gaoul commented on src/components/form.js
> +                item.element.parentNode.style.border = '1px solid red';
Т.е. сейчас получается так, я открываю страницу логина и вижу инпуты сразу выделенные красным, при этом еще ничего на самой форме не вводил.
Мне кажется тут это лучше удалить

2024-02-07 11:26 UTC, Amil-Gaoul commented on styles/bootstrap.min.css
Вот этого файла тут по идее быть не должно, bootstrap же был установлен через npm, получается что стили будут импортированы в app.js, а файл надо удалить и подключение в html тоже

2024-02-07 11:26 UTC, Amil-Gaoul commented on src/app.js
> +//import 'bootstrap/dist/css/bootstrap.min.css';
Эту строчку можно раскомментировать

2024-02-07 11:26 UTC, Amil-Gaoul commented on templates/income.html
> +            <a href="#/create-income" class="btn border  col col-xxl-3 category_card btn_add_item">
Не хватает класса d-flex, крестик в таком случае не встает по центру кнопки

2024-02-07 11:26 UTC, Amil-Gaoul commented on templates/income.html
> +            <a href="#/create-income" class="btn border  col col-xxl-3 category_card btn_add_item">
Из-за класса btn кстати рамка у этой кнопки отличается от остальных элементов

2024-02-08 11:11 UTC, AlekseiZhukov commented on styles/bootstrap.min.css
проблема в том, что мои стили перекрывают некоторые бутстраповские и если бутстрап собирает вебпак они в index.html становятся после моих

2024-02-08 11:12 UTC, AlekseiZhukov commented on src/components/form.js
> +                item.element.parentNode.style.border = '1px solid red';
Это убрал

2024-02-08 11:22 UTC, AlekseiZhukov commented on src/app.js
> +//import 'bootstrap/dist/css/bootstrap.min.css';
А, понял. Импортирую свои стили в app.js после бутстраповских и тогда все ок

2024-02-08 11:23 UTC, AlekseiZhukov commented on templates/income.html
> +            <a href="#/create-income" class="btn border  col col-xxl-3 category_card btn_add_item">
У меня все поправлено в классе btn_add_item

2024-02-08 16:26 UTC, Amil-Gaoul commented on src/app.js
> +//import 'bootstrap/dist/css/bootstrap.min.css';
Тут обычно как делается. Если нужно перебить бутстраповские классы, то лучше заводить свой класс, например, я хочу чтобы бутстраповская кнопка всегда растягивалась на всю ширину, поэтому я создаю свой класс и в стилях так же учитываю бутстраповский:
```css
  .my-btn.btn {
    width: 100%;
  }
```
В html конечно же оба класса к кнопке применяются, в таком случае, если бутстрап подключается после, то за счет специфичности веса селекторов твои стили бутстраповские перебьют и в то же время их не поломают на случай, если вдруг понадобится использовать бутстраповскую кнопку на той же странице

2024-02-08 16:27 UTC, Amil-Gaoul approved these changes

2024-02-08 16:30 UTC, Amil-Gaoul commented on src/app.js
> +//import 'bootstrap/dist/css/bootstrap.min.css';
Если конечно ты понимаешь что на всем проекте у тебя будут только твой вариант кнопок, то можно сильно не заморачиваться, но лучше всегда закладывать на будущее, что вдруг что-то поменяется, поэтому в идеале должен быть свой класс, который оказывает влияние на стили

2024-02-09 06:31 UTC, merged